[local]
local

[mongodb]
mongodb.mitha.fun

[redis]
redis.mitha.fun

[mysql]
mysql.mitha.fun 

[rabbitmq]
rabbitmq.mitha.fun

[cart]
cart.mitha.fun

[user]
user.mitha.fun

[catalogue]
catalogue.mitha.fun

[shipping]
shipping.mitha.fun

[payment]
payment.mitha.fun

[frontend]
frontend.mitha.fun






[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321