[local]
local

[mongodb]
local

[redis]
local

[mysql]
local

[rabbitmq]
local

[cart]
local

[user]
local

[catalogue]
local

[shipping]
local

[payment]
local

[frontend]
local






[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321