- name: "Setting up {{ component }} server"
  hosts: localhost
  become: yes

  vars_files:
    - group_vars/all.yaml

  pre_tasks:
    - name: Load MySQL specific variables
      include_vars:
        file: group_vars/mysql.yaml
      when: component == "mysql"

  roles:
    - "{{ component }}"