- name: appsetup for catalogue by using import role
  ansible.builtin.import_role:
        name: common
        tasks_from: user-appsetup.yaml

      
- name: appsetup for payment by using import role
  ansible.builtin.import_role:
        name: common
        tasks_from: python.yaml



- name: servicesetup using import role
  ansible.builtin.import_role:
        name: common
        tasks_from: service-setup.yaml