- name: creating user-app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: user-appsetup.yaml

- name: installing nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml

- name: setting up service file
  ansible.builtin.import_role:
    name: common
    tasks_from: service-setup.yaml

- name: copying mongo.repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: installing mongo client mongosh
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: connect to mongodb client
  ansible.builtin.command:
    cmd: mongosh {{ MONGODB_HOST }} --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output

- name: connecting to mongodb
  ansible.builtin.shell:
    cmd: mongosh --host {{ MONGODB_HOST }} </app/db/master-data.js
  when: catalogue_output.stdout | int < 0