- name: Install required system packages
  ansible.builtin.package:
    name:
      - python3
      - gcc
      - python3-devel
    state: present


- name: Install pip packages from requirements
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3


